name: Build ImmortalWrt

on:
    workflow_dispatch:

env:
    CLONE_COMMAND: git clone -b openwrt-21.02 --depth 1 https://github.com/immortalwrt/immortalwrt.git
    REPO_NAME: immortalwrt

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone from github
              uses: actions/checkout@v3

            - name: Clone immortalwrt repo
              run: |
                  $CLONE_COMMAND

            - name: Copy config to source code
              run: |
                  cp -f .config feeds.conf.default diy.sh $REPO_NAME/

            - name: Install the software packages required for compilation
              run: |
                  sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

            - name: Get the dependency of immortalwrt
              run: |
                  cd $REPO_NAME
                  chmod +x diy.sh
                  ./diy.sh
                  ./scripts/feeds update -a && ./scripts/feeds install -a

            - name: Copy config to source code
              run: |
                  cp -f .config feeds.conf.default diy.sh $REPO_NAME/

            - name: Upload config before build
              uses: actions/upload-artifact@v3
              with:
                  name: config before build
                  path: .config

            - name: Build immortalwrt
              run: |
                  cd $REPO_NAME
                  # 默认make -j$(nproc)，代表多线程编译。如果求稳想看报错信息，可以使用make -j1 V=99代替
                  make -j1 V=99
                  pwd
                  ls

            - name: Move results to root
              run: |
                  cd /home/runner/work/Actions-ImmortalWrt/Actions-ImmortalWrt/$REPO_NAME
                  mv bin/targets ../
                  cd ..

            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                  name: ImmortalWrt_build_files
                  path: targets
